name: Black

on: [push]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python

      uses: actions/setup-python@v5

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Check code formatting with black
      run: black --check $(git ls-files '*.py')
