name: Ruff

on: [push]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python

      uses: actions/setup-python@v5

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ruff
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Analyzing the code with ruff
      run: ruff check $(git ls-files '*.py')
